[package]
edition.workspace = true
name = "archive_sync"
publish = false
license.workspace = true
version.workspace = true

[dependencies]
postgresql_archive = { path = "../../postgresql_archive", features = ["blocking"] }
tempfile = { workspace = true }
