[workspace]
default-members = [
    "postgresql_archive",
    "postgresql_commands",
    "postgresql_embedded",
    "postgresql_extensions",
]
members = [
    "examples/*",
    "postgresql_archive",
    "postgresql_commands",
    "postgresql_embedded",
    "postgresql_extensions",
]
resolver = "2"

[workspace.package]
authors = ["Brian Heineman <brian.heineman@gmail.com>"]
categories = ["database"]
edition = "2021"
keywords = ["postgresql", "postgres", "embedded", "database", "server"]
license = "(Apache-2.0 OR MIT) AND PostgreSQL"
repository = "https://github.com/theseus-rs/postgresql-embedded"
version = "0.15.0"

[workspace.dependencies]
anyhow = "1.0.86"
async-trait = "0.1.81"
blake2 = "0.10.6"
criterion = "0.5.1"
flate2 = "1.0.31"
hex = "0.4.3"
home = "0.5.9"
http = "1.1.0"
human_bytes = { version = "0.4.3", default-features = false }
indoc = "2.0.5"
md-5 = "0.10.6"
num-format = "0.4.4"
quick-xml = "0.36.1"
rand = "0.8.5"
regex = "1.10.6"
reqwest = { version = "0.12.5", default-features = false }
reqwest-middleware = "0.3.1"
reqwest-retry = "0.6.0"
reqwest-tracing = "0.5.2"
semver = "1.0.23"
serde = "1.0.204"
serde_json = "1.0.122"
sha1 = "0.10.6"
sha2 = "0.10.8"
sha3 = "0.10.8"
sqlx = { version = "0.8.0", default-features = false, features = ["postgres"] }
tar = "0.4.41"
target-triple = "0.1.3"
test-log = "0.2.16"
tempfile = "3.11.0"
thiserror = "1.0.63"
tokio = "1.39.2"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
url = "2.5.2"
xz2 = "0.1.7"
zip = "2.1.6"

[workspace.metadata.release]
shared-version = true
dependent-version = "upgrade"
tag-name = "v{{version}}"
