[workspace]
default-members = ["postgresql_archive", "postgresql_embedded"]
members = ["postgresql_archive", "postgresql_embedded"]
resolver = "2"

[workspace.package]
authors = ["Brian Heineman <brian.heineman@gmail.com>"]
categories = ["database"]
edition = "2021"
keywords = ["postgresql", "ffi", "database"]
license = "(Apache-2.0 OR MIT) AND PostgreSQL"
repository = "https://github.com/theseus-rs/postgresql_embedded"
version = "0.1.0"

[workspace.dependencies]
anyhow = { version = "1.0" }
bytes = { version = "1.5" }
flate2 = { version = "1.0" }
hex = { version = "0.4" }
home = { version = "0.5" }
human_bytes = { version = "0.4", default-features = false }
lazy_static = { version = "1.4" }
num-format = { version = "0.4" }
rand = { version = "0.8" }
regex = { version = "1.10" }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
sha2 = { version = "0.10" }
tar = { version = "0.4" }
target-triple = { version = "0.1" }
test-log = { version = "0.2" }
tempfile = { version = "3.10" }
thiserror = { version = "1.0" }
tokio = { version = "1.36", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }

[workspace.metadata.release]
shared-version = true
dependent-version = "upgrade"
tag-name = "v{{version}}"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
