[package]
authors.workspace = true
build = "build/build.rs"
categories.workspace = true
description = "Install and run a PostgreSQL database locally on Linux, MacOS or Windows. PostgreSQL can be bundled with your application, or downloaded on demand."
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "postgresql_embedded"
repository = "https://github.com/theseus-rs/postgresql-embedded/tree/main/postgresql_embedded"
version.workspace = true

[build-dependencies]
anyhow = { workspace = true }
postgresql_archive = { path = "../postgresql_archive", version = "0.4.1" }
tokio = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
home = { workspace = true }
lazy_static = { workspace = true }
postgresql_archive = { path = "../postgresql_archive", version = "0.4.1" }
rand = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
test-log = { workspace = true }
tokio = { workspace = true }

[features]
default = ["bundled"]
blocking = ["tokio"]
bundled = []
tokio = ["dep:tokio"]

[package.metadata.release]
dependent-version = "upgrade"

[package.metadata.docs.rs]
no-default-features = true
features = ["blocking", "tokio"]
targets = ["x86_64-unknown-linux-gnu"]

[[bench]]
harness = false
name = "embedded"
