[package]
authors.workspace = true
categories.workspace = true
description = "A library for downloading and extracting PostgreSQL archives"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "postgresql_archive"
repository = "https://github.com/theseus-rs/postgresql-embedded/tree/main/postgresql_archive"
version.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
flate2 = { workspace = true }
hex = { workspace = true }
human_bytes = { workspace = true }
lazy_static = { workspace = true }
num-format = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
reqwest-retry = { workspace = true }
reqwest-tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tar = { workspace = true }
target-triple = { workspace = true }
task-local-extensions = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
hex = { workspace = true }
test-log = { workspace = true }
tokio = { workspace = true }

[features]
default = []
blocking = ["dep:tokio"]

[package.metadata.docs.rs]
features = ["blocking"]
targets = ["x86_64-unknown-linux-gnu"]

[[bench]]
harness = false
name = "archive"
