[package]
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "postgresql_archive"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
flate2 = { workspace = true }
lazy_static = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tar = { workspace = true }
target-triple = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
hex = { workspace = true }
tokio = { workspace = true }

[features]
default = []
blocking = ["dep:tokio"]
