name: Build & Test

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  RUST_LOG: "info"
  RUST_LOG_SPAN_EVENTS: full

on:
  workflow_call:
    inputs:
      ref:
        default: ${{ github.ref }}
        type: string

jobs:
  build:
    name: ${{ matrix.platform }} (${{ matrix.target }}) (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux-x64
          - macos-arm64
          - macos-x64
          #- windows-x64

        include:
          - platform: linux-x64
            os: ubuntu-22.04
          - platform: macos-arm64
            os: macos-14
          - platform: macos-x64
            os: macos-13
          #- platform: windows-x64
          #  os: windows-2022

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable

    - name: Enable caching
      uses: Swatinem/rust-cache@v2

    - name: Tests
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        cargo test --workspace --all-features
