name: Build & Test

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

on:
  workflow_call:
    inputs:
      ref:
        default: ${{ github.ref }}
        type: string

jobs:
  build:
    name: ${{ matrix.platform }} (${{ matrix.target }}) (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux-x64
          - macos-arm64
          - macos-x64
          - windows-x64

        include:
          - platform: linux-x64
            os: ubuntu-latest
          - platform: macos-arm64
            os: macos-14
          - platform: macos-x64
            os: macos-13
          - platform: windows-x64
            os: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable

    - name: Tests
      run: |
        cargo test --package postgresql_archive --no-default-features
        cargo test --package postgresql_archive --all-features
        cargo test --package postgresql_embedded --no-default-features
        cargo test --package postgresql_embedded --features blocking
        cargo test --package postgresql_embedded --features bundled
        cargo test --package postgresql_embedded --features tokio
        cargo test --package postgresql_embedded --all-features

    - name: Upload coverage reports to Codecov
      if: ${{ matrix.platform == 'linux-x64' }}
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
