name: Fast checks

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Install cargo audit
        run: cargo install cargo-audit

      # Ignoring RUSTSEC-2023-0071 as it only occurs in a dependency used in an example
      # and is not exploitable in the context of this project.
      #
      # Crate:     rsa
      # Version:   0.9.6
      # Title:     Marvin Attack: potential key recovery through timing sidechannels
      # Date:      2023-11-22
      # ID:        RUSTSEC-2023-0071
      # URL:       https://rustsec.org/advisories/RUSTSEC-2023-0071
      # Severity:  5.9 (medium)
      # Solution:  No fixed upgrade is available!
      # Dependency tree:
      # rsa 0.9.6
      # └── sqlx-mysql 0.7.3
      #     ├── sqlx-macros-core 0.7.3
      #     │   └── sqlx-macros 0.7.3
      #     │       └── sqlx 0.7.3
      #     │           └── sqlx_embedded 0.4.1
      #     └── sqlx 0.7.3
      - name: Audit dependencies
        run: cargo audit --ignore RUSTSEC-2023-0071

  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Check the project
        run: |
          cargo check --workspace --all-targets --features blocking
          cargo check --workspace --all-targets --features bundled
          cargo check --workspace --all-targets --features tokio
          cargo check --workspace --all-targets --all-features

  clippy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Check lints
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          cargo clippy --all-targets --all-features --examples --tests

  deny:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Install cargo deny
        run: cargo install cargo-deny
      - name: Check licenses
        run: cargo deny check --allow duplicate

  doc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --workspace --no-deps --document-private-items --all-features

  fmt:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo fmt --all --check
