name: Fast checks

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

on:
  workflow_call:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Install cargo audit
        run: cargo install cargo-audit
      - name: Audit dependencies
        run: cargo audit

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Check the project
        run: |
          cargo check --workspace --all-targets --features blocking
          cargo check --workspace --all-targets --features bundled
          cargo check --workspace --all-targets --features tokio
          cargo check --workspace --all-targets --all-features

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Check lints
        run: |
          cargo clippy --workspace --features blocking
          cargo clippy --workspace --features bundled
          cargo clippy --workspace --features tokio
          cargo clippy --workspace --all-features

  deny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Install cargo deny
        run: cargo install cargo-deny
      - name: Check licenses
        run: cargo deny check --allow duplicate

  doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --workspace --no-deps --document-private-items --all-features

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all --check

  vet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Install cargo vet
        run: cargo install cargo-vet
      - name: Vet thirdparty dependencies
        run: cargo vet check
