name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-22.04
    steps:
      - name: Get PR head ref
        if: ${{ github.event_name == 'pull_request' }}
        id: pr_head_ref
        run: |
          echo "ref=refs/pull/${{ github.event.pull_request.number }}/head" >> $GITHUB_OUTPUT
    outputs:
      ref: >-
        ${{
          (github.event_name == 'pull_request' && startsWith(github.head_ref, 'release/v'))
          && steps.pr_head_ref.outputs.ref
          || github.ref
        }}

  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml

  build:
    name: Build & Test
    needs: [initialize, checks]
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ needs.init.outputs.ref }}
