name: Benchmarks

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          components: 'llvm-tools-preview'
          toolchain: stable

      - name: Enable caching
        uses: Swatinem/rust-cache@v2

      - name: Install benchmarking tools
        uses: bencherdev/bencher@main

      - name: Run benchmarks
        env:
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
          BENCHER_PROJECT: theseus-rs-postgresql-embedded
          BENCHER_ADAPTER: rust_criterion
        run: |
          cargo bench --bench archive --features blocking -- --output-format criterion | \
            bencher run \
              --branch $GITHUB_HEAD_REF \
              --ci-number "${{ github.event.number }}" \
              --github-actions "${{ secrets.GITHUB_TOKEN }}" \
              --err
          cargo bench --bench embedded --features blocking -- --output-format criterion | \
            bencher run \
              --branch $GITHUB_HEAD_REF \
              --ci-number "${{ github.event.number }}" \
              --github-actions "${{ secrets.GITHUB_TOKEN }}" \
              --err
